development:
  adapter: mysql2
  database: expresso_rasante_development
  user: root
  password: budal33
test:
  adapter: mysql2
  database: expresso_rasante_test
  user: root
  password: budal33

production:
  adapter: mysql2
  database: expresso_rasante_production
  user: root
  password: budal33